package com.hnsh.dialogue.sql.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.hnsh.dialogue.bean.db.AppInfo;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "APP_INFO".
*/
public class AppInfoDao extends AbstractDao<AppInfo, Long> {

    public static final String TABLENAME = "APP_INFO";

    /**
     * Properties of entity AppInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PackageName = new Property(1, String.class, "packageName", false, "PACKAGE_NAME");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property Icon = new Property(3, byte[].class, "icon", false, "ICON");
        public final static Property PackagePath = new Property(4, String.class, "packagePath", false, "PACKAGE_PATH");
        public final static Property VersionName = new Property(5, String.class, "versionName", false, "VERSION_NAME");
        public final static Property VersionCode = new Property(6, int.class, "versionCode", false, "VERSION_CODE");
        public final static Property IsSystem = new Property(7, boolean.class, "isSystem", false, "IS_SYSTEM");
        public final static Property IsToDesktop = new Property(8, boolean.class, "isToDesktop", false, "IS_TO_DESKTOP");
    }


    public AppInfoDao(DaoConfig config) {
        super(config);
    }
    
    public AppInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"APP_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PACKAGE_NAME\" TEXT UNIQUE ," + // 1: packageName
                "\"NAME\" TEXT," + // 2: name
                "\"ICON\" BLOB," + // 3: icon
                "\"PACKAGE_PATH\" TEXT," + // 4: packagePath
                "\"VERSION_NAME\" TEXT," + // 5: versionName
                "\"VERSION_CODE\" INTEGER NOT NULL ," + // 6: versionCode
                "\"IS_SYSTEM\" INTEGER NOT NULL ," + // 7: isSystem
                "\"IS_TO_DESKTOP\" INTEGER NOT NULL );"); // 8: isToDesktop
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"APP_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        byte[] icon = entity.getIcon();
        if (icon != null) {
            stmt.bindBlob(4, icon);
        }
 
        String packagePath = entity.getPackagePath();
        if (packagePath != null) {
            stmt.bindString(5, packagePath);
        }
 
        String versionName = entity.getVersionName();
        if (versionName != null) {
            stmt.bindString(6, versionName);
        }
        stmt.bindLong(7, entity.getVersionCode());
        stmt.bindLong(8, entity.getIsSystem() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsToDesktop() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AppInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String packageName = entity.getPackageName();
        if (packageName != null) {
            stmt.bindString(2, packageName);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        byte[] icon = entity.getIcon();
        if (icon != null) {
            stmt.bindBlob(4, icon);
        }
 
        String packagePath = entity.getPackagePath();
        if (packagePath != null) {
            stmt.bindString(5, packagePath);
        }
 
        String versionName = entity.getVersionName();
        if (versionName != null) {
            stmt.bindString(6, versionName);
        }
        stmt.bindLong(7, entity.getVersionCode());
        stmt.bindLong(8, entity.getIsSystem() ? 1L: 0L);
        stmt.bindLong(9, entity.getIsToDesktop() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public AppInfo readEntity(Cursor cursor, int offset) {
        AppInfo entity = new AppInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // packageName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3), // icon
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // packagePath
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // versionName
            cursor.getInt(offset + 6), // versionCode
            cursor.getShort(offset + 7) != 0, // isSystem
            cursor.getShort(offset + 8) != 0 // isToDesktop
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AppInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPackageName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIcon(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
        entity.setPackagePath(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setVersionName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setVersionCode(cursor.getInt(offset + 6));
        entity.setIsSystem(cursor.getShort(offset + 7) != 0);
        entity.setIsToDesktop(cursor.getShort(offset + 8) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(AppInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(AppInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(AppInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
