package com.hnsh.dialogue.sql.dao;

import com.hnsh.dialogue.bean.cbs.MessageContent;
import com.hnsh.dialogue.bean.db.AppInfo;
import com.hnsh.dialogue.bean.db.LanguageSeletedEntity;
import com.hnsh.dialogue.bean.db.QACategoryBean;
import com.hnsh.dialogue.bean.db.QAInfoBean;
import com.hnsh.dialogue.bean.db.QuestionInfoBean;
import com.hnsh.dialogue.bean.db.TranslationInfoBean;
import com.hnsh.dialogue.bean.db.TypeInfoBean;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appInfoDaoConfig;
    private final DaoConfig languageSeletedEntityDaoConfig;
    private final DaoConfig qACategoryBeanDaoConfig;
    private final DaoConfig qAInfoBeanDaoConfig;
    private final DaoConfig questionInfoBeanDaoConfig;
    private final DaoConfig translationInfoBeanDaoConfig;
    private final DaoConfig typeInfoBeanDaoConfig;
    private final DaoConfig messageContentDaoConfig;

    private final AppInfoDao appInfoDao;
    private final LanguageSeletedEntityDao languageSeletedEntityDao;
    private final QACategoryBeanDao qACategoryBeanDao;
    private final QAInfoBeanDao qAInfoBeanDao;
    private final QuestionInfoBeanDao questionInfoBeanDao;
    private final TranslationInfoBeanDao translationInfoBeanDao;
    private final TypeInfoBeanDao typeInfoBeanDao;
    private final MessageContentDao messageContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appInfoDaoConfig = daoConfigMap.get(AppInfoDao.class).clone();
        appInfoDaoConfig.initIdentityScope(type);

        languageSeletedEntityDaoConfig = daoConfigMap.get(LanguageSeletedEntityDao.class).clone();
        languageSeletedEntityDaoConfig.initIdentityScope(type);

        qACategoryBeanDaoConfig = daoConfigMap.get(QACategoryBeanDao.class).clone();
        qACategoryBeanDaoConfig.initIdentityScope(type);

        qAInfoBeanDaoConfig = daoConfigMap.get(QAInfoBeanDao.class).clone();
        qAInfoBeanDaoConfig.initIdentityScope(type);

        questionInfoBeanDaoConfig = daoConfigMap.get(QuestionInfoBeanDao.class).clone();
        questionInfoBeanDaoConfig.initIdentityScope(type);

        translationInfoBeanDaoConfig = daoConfigMap.get(TranslationInfoBeanDao.class).clone();
        translationInfoBeanDaoConfig.initIdentityScope(type);

        typeInfoBeanDaoConfig = daoConfigMap.get(TypeInfoBeanDao.class).clone();
        typeInfoBeanDaoConfig.initIdentityScope(type);

        messageContentDaoConfig = daoConfigMap.get(MessageContentDao.class).clone();
        messageContentDaoConfig.initIdentityScope(type);

        appInfoDao = new AppInfoDao(appInfoDaoConfig, this);
        languageSeletedEntityDao = new LanguageSeletedEntityDao(languageSeletedEntityDaoConfig, this);
        qACategoryBeanDao = new QACategoryBeanDao(qACategoryBeanDaoConfig, this);
        qAInfoBeanDao = new QAInfoBeanDao(qAInfoBeanDaoConfig, this);
        questionInfoBeanDao = new QuestionInfoBeanDao(questionInfoBeanDaoConfig, this);
        translationInfoBeanDao = new TranslationInfoBeanDao(translationInfoBeanDaoConfig, this);
        typeInfoBeanDao = new TypeInfoBeanDao(typeInfoBeanDaoConfig, this);
        messageContentDao = new MessageContentDao(messageContentDaoConfig, this);

        registerDao(AppInfo.class, appInfoDao);
        registerDao(LanguageSeletedEntity.class, languageSeletedEntityDao);
        registerDao(QACategoryBean.class, qACategoryBeanDao);
        registerDao(QAInfoBean.class, qAInfoBeanDao);
        registerDao(QuestionInfoBean.class, questionInfoBeanDao);
        registerDao(TranslationInfoBean.class, translationInfoBeanDao);
        registerDao(TypeInfoBean.class, typeInfoBeanDao);
        registerDao(MessageContent.class, messageContentDao);
    }
    
    public void clear() {
        appInfoDaoConfig.clearIdentityScope();
        languageSeletedEntityDaoConfig.clearIdentityScope();
        qACategoryBeanDaoConfig.clearIdentityScope();
        qAInfoBeanDaoConfig.clearIdentityScope();
        questionInfoBeanDaoConfig.clearIdentityScope();
        translationInfoBeanDaoConfig.clearIdentityScope();
        typeInfoBeanDaoConfig.clearIdentityScope();
        messageContentDaoConfig.clearIdentityScope();
    }

    public AppInfoDao getAppInfoDao() {
        return appInfoDao;
    }

    public LanguageSeletedEntityDao getLanguageSeletedEntityDao() {
        return languageSeletedEntityDao;
    }

    public QACategoryBeanDao getQACategoryBeanDao() {
        return qACategoryBeanDao;
    }

    public QAInfoBeanDao getQAInfoBeanDao() {
        return qAInfoBeanDao;
    }

    public QuestionInfoBeanDao getQuestionInfoBeanDao() {
        return questionInfoBeanDao;
    }

    public TranslationInfoBeanDao getTranslationInfoBeanDao() {
        return translationInfoBeanDao;
    }

    public TypeInfoBeanDao getTypeInfoBeanDao() {
        return typeInfoBeanDao;
    }

    public MessageContentDao getMessageContentDao() {
        return messageContentDao;
    }

}
