package com.hnsh.dialogue.sql.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.hnsh.dialogue.bean.db.LanguageSeletedEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "LANGUAGE_SELETED_ENTITY".
*/
public class LanguageSeletedEntityDao extends AbstractDao<LanguageSeletedEntity, Long> {

    public static final String TABLENAME = "LANGUAGE_SELETED_ENTITY";

    /**
     * Properties of entity LanguageSeletedEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LanId = new Property(1, int.class, "lanId", false, "LAN_ID");
        public final static Property Count = new Property(2, int.class, "count", false, "COUNT");
        public final static Property LastClickTime = new Property(3, long.class, "lastClickTime", false, "LAST_CLICK_TIME");
    }


    public LanguageSeletedEntityDao(DaoConfig config) {
        super(config);
    }
    
    public LanguageSeletedEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LANGUAGE_SELETED_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"LAN_ID\" INTEGER NOT NULL UNIQUE ," + // 1: lanId
                "\"COUNT\" INTEGER NOT NULL ," + // 2: count
                "\"LAST_CLICK_TIME\" INTEGER NOT NULL );"); // 3: lastClickTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LANGUAGE_SELETED_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LanguageSeletedEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLanId());
        stmt.bindLong(3, entity.getCount());
        stmt.bindLong(4, entity.getLastClickTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LanguageSeletedEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLanId());
        stmt.bindLong(3, entity.getCount());
        stmt.bindLong(4, entity.getLastClickTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public LanguageSeletedEntity readEntity(Cursor cursor, int offset) {
        LanguageSeletedEntity entity = new LanguageSeletedEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // lanId
            cursor.getInt(offset + 2), // count
            cursor.getLong(offset + 3) // lastClickTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LanguageSeletedEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLanId(cursor.getInt(offset + 1));
        entity.setCount(cursor.getInt(offset + 2));
        entity.setLastClickTime(cursor.getLong(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(LanguageSeletedEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(LanguageSeletedEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(LanguageSeletedEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
